[project]
name = "jeu-ski-alpin"
version = "0.1.0"
description = "Add your description here"
readme = "README.md"
requires-python = ">=3.12.4"
dependencies = [
    "coverage>=7.13.1",
    "coverage-badge>=1.1.2",
    "flake8>=7.3.0",
    "pygame>=2.6.1",
]
